spring.application.name=service-management
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-minutes=${JWT_EXP_MINUTES}